version: '3.8'

services:
  readbook:
    build: ./
    command: ./readbook
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=dreamer8

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=dreamer8
    ports:
      - 5432:5432